name: Cypress Automation Tests
on:
  workflow_dispatch:
jobs:
  job1:
    name: cypress-run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Packages
        run: npm install
      - name: Run Tests
        run: npx cypress run --spec $(node cypress-parallel.js ${{ matrix.containers }} 2)
        continue-on-error: true
      - name: Upload Mochawesome results
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-${{ matrix.containers }}
          path: cypress/reports/

  merge-and-publish:
    name: reports
    if: always()
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        run: |
          mkdir -p artifacts
          for i in 0 1; do
            npx @actions/artifact-cli download --name mochawesome-$i --path artifacts || true
          done

      - name: Merge mochawesome reports
        run: |
          mkdir -p merged-reports
          find artifacts -name '*.json' -exec cp {} merged-reports/ \;
          npx mochawesome-merge merged-reports/*.json > merged-reports/merged.json
          npx marge merged-reports/merged.json -f index -o mochawesome-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report