name: Cypress Automation Tests
on:
  workflow_dispatch:
jobs:
  job1:
    name: cypress-run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Packages
        run: npm install
      - name: Run Tests
        run: npx cypress run --spec $(node cypress-parallel.js ${{ matrix.containers }} 2)
        continue-on-error: true
      - name: Upload Mochawesome results
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-${{ matrix.containers }}
          path: cypress/reports/

  merge-and-publish:
    name: reports
    if: always()
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: cypress/reports

      # - name: Merge Allure Results from all machines
      #   run: |
      #         mkdir -p merged-results
      #         for folder in cypress/reports/mochawesome-*; do
      #           if [ -d "$folder" ]; then
      #             echo "Merging from $folder"
      #             rsync -a "$folder"/ merged-results/
      #           fi
      #         done
      #         echo "Final merged contents:"
      #         ls -lh merged-results

      #         npx mochawesome-merge merged-results/*.json > merged-results/merged.json
      #         npx marge merged-results/merged.json -f index -o mochawesome-report

      - name: Merge JSONs
        run: |
          mkdir merged-json
          find cypress/reports -name '*.json' -exec cp {} merged-json/ \;
          npx mochawesome-merge merged-json/*.json > merged-json/merged.json
          npx marge merged-json/merged.json -f index -o mochawesome-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report